; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28314.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\clmesnil\AppData\Local\Temp\217\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
